sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t sambhaab-raaj/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sambhaab-raaj/docker-react npm run test
